// Import Style //
import "@/app/ui/style/index.scss";

// Import Font //
import { inter } from "./ui/fonts/inter";

// Metadata //
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Import Cookies //
import { cookies } from "next/headers";

// Import Components //
import Header from "./ui/layout/Header";
import Footer from "./ui/layout/Footer";

// Import Context //
import AuthProvider from "./context/AuthContext";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const isUserConnected = cookieStore.get("userToken") ? true : false;

  return (
    <html lang="fr">
      <body className={inter.className}>
        <AuthProvider isUserConnected={isUserConnected}>
          <Header />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
