// Import Style //
import "@/app/ui/style/index.scss";

// Import Font //
import { inter } from "./ui/fonts/inter";

// Metadata //
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import Components //
import Header from "./ui/layout/Header";
import Footer from "./ui/layout/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
